### ISSUE TITLE
CR error

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#576]
yellow error pops justs before the red one so they tied together

Getting random element from empty collection.
Verse.Log:Warning(String)
Verse.GenCollection:RandomElement(IEnumerable`1)
RumoursAndDeception.InteractionWorker_ChattedAboutSomeone:ChooseChattedAbout(Pawn, Pawn)
RumoursAndDeception.InteractionWorker_ChattedAboutSomeone:RandomSelectionWeight(Pawn, Pawn)
Hospitality.Detouring.<>c__DisplayClass4:<TryInteractRandomly>b__0(InteractionDef)
Verse.GenCollection:TryRandomElementByWeight(IEnumerable`1, Func`2, InteractionDef&)
Hospitality.Detouring.Pawn_InteractionsTracker:TryInteractRandomly(Pawn_InteractionsTracker)
RimWorld.Pawn_InteractionsTracker:InteractionsTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

Exception in RimWorld.ThinkNode_ConditionalCanDoConstantThinkTreeJobNow TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at Combat_Realism.JobGiver_TakeAndEquip.TryGiveJob (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Combat_Realism.Detours_ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
RimWorld.ThinkNode_Conditional:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
Verse.AI.Pawn_JobTracker:DetermineNextConstantThinkTreeJob()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by sidfu** [comment]
update

new info this error happened when i had a trader and one of the traders was changed into being my uncle

**Comment by sidfu** [comment]
update more info after this error came and went my guys that do animal training keep grabbing whole grass plants out of he ground to thry to do traning with

**Comment by skyarkhangel** [comment]
fixed?

**Comment by sidfu** [comment]
the first error is fixed had a trader and it didnt pop but the second error is still present. it seems to be triggering on my animal trainer he keeps grabing whole grass plants off the ground and useing them to train.

**Comment by skyarkhangel** [comment]
ok

**Comment by sidfu** [comment]
hmm the cr error still poped up at start of new game with newest. think it was related to the random npc that spawns with u for captureing. it stoped poping once he got out of range.

**Comment by sidfu** [comment]
ok i was correct when this error pops
Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.InvalidCastException: Cannot cast from source type to destination type.
  at Combat_Realism.RightTools.EquipRigthTool (Verse.Pawn pawn, RimWorld.StatDef def) [0x00000] in <filename unknown>:0 
  at Combat_Realism.Detours_ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
RimWorld.ThinkNode_Conditional:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
Psychology.Detour._Pawn_JobTracker:_EndCurrentJob(Pawn_JobTracker, JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

is when u set your animal guys to train animals. what happens is if u dont have them carry the items to train they will grab growing grass of the ground(yeah not harvest just the whole still growing plant) and use it.

**Comment by skyarkhangel** [comment]
Psychology mod is still not compatible and NOT RECOMMENDED with hardcore SK.
